Repository PKNU-JavaStudy/mo.zip_frontend, pull requests merged in 2024-05, with the labels that each got.

#13 [#12]Docs: 메인페이지 주석추가
  index.html
Labels: documentation

#22 프로젝트모집작성 페이지 퍼블리싱
  css/recruit_create.css
  recruit_create.html
Labels: enhancement

#27 프로젝트모집작성 페이지 레이아웃 수정
  css/recruit_create.css
  recruit_create.html
Labels: bug

#29 [#25]Feat: 회원가입 html, css 파일 생성
  css/join.css
  join.html
Labels: documentation

#33 프로젝트자랑 작성 페이지 퍼블리싱 완료
  css/show_create.css
  show_create.html
Labels: enhancement

#35 로그인페이지 퍼블리싱
  css/login.css
  login.html
Labels: enhancement

#42 Topic/mypage
  css/mypage.css
  mypage.html
Labels: bug

#45 Topic/mypage edit
  css/mypage_edit.css
  mypage_edit.html
Labels: enhancement

#48 프로젝트 자랑 페이지 수정
  css/show_create.css
  show_create.html
Labels: enhancement

#49 [#47]Feat: 관련페이지 연결
  common/header.js
  index.html
  recruit_list.html
  show_list.html
Labels: enhancement

#52 Fix/modal
  js/common.js
  recruit_create.html
  recruit_detail.html
  recruit_list.html
Labels: bug

#55 Topic/detail02
  css/recruit_detail.css
  css/show_detail.css
  recruit_detail.html
  show_detail.html
Labels: bug

#57 Fix/detail modal
  css/recruit_detail.css
  css/show_detail.css
  js/common.js
  recruit_detail.html
  show_detail.html
Labels: bug

#62 [#61]Design: 담당페이지 CSS 수정
  show_create.html
Labels: documentation

#67 [#66]Feat: 아이디찾기 파일 생성
  css/find_id.css
  find_id.html
Labels: enhancement

#70 [#68]Feat: 비밀번호 찾기 파일 생성
  css/find_password.css
  find_password.html
Labels: enhancement

#72 [#71]Feat: 로그인,회원가입 페이지 코드 리팩토링
  css/join.css
  css/login.css
  join.html
  js/join_effect.js
  login.html
Labels: enhancement

#81 [#80]Design: 작성(create)페이지 CSS 통합
  css/create.css
  css/recruit_create.css
  css/show_create.css
  recruit_create.html
  show_create.html
Labels: enhancement

#83 [#79]Feat: 담당 페이지 css 통합
  css/mypage.css
  css/mypage_edit.css
  mypage_edit.html
Labels: enhancement

#88 [#86]프로젝트모집,자랑 작성페이지 UI 수정
  recruit_create.html
  show_create.html
Labels: documentation

#89 Topic/kanban
  .idea/.gitignore
  .idea/misc.xml
  .idea/mo.zip_frontend.iml
  .idea/modules.xml
  .idea/vcs.xml
  css/create.css
  css/list.css
  css/show_list.css
  css/team_note.css
  css/team_note_list.css
  js/01jaeyoung.js
  js/02donggun.js
  js/03yoonji.js
  js/04jisoo.js
  js/kanban.js
  recruit_list.html
  show_list.html
  team_note.html
  team_note_list.html
Labels: enhancement

#91 Feat: 담당페이지 ui 수정
  css/mypage.css
  css/user.css
  join.html
  js/join_effect.js
  login.html
  mypage_edit.html
Labels: enhancement

#92 [#65]Feat: 마이페이지 수정 아이콘 동적 구현
  .idea/misc.xml
  .idea/mo.zip_frontend.iml
  css/mypage.css
  js/02donggun.js
  js/join_effect.js
  mypage_edit.html
Labels: enhancement

#94 [#93]Feat: 유효성검사 및 로그인 순서교체
  css/mypage.css
  join.html
  js/02donggun.js
  mypage_edit.html
Labels: enhancement

#98 Feat: 마이페이지 수정
  team_note.html
Labels: enhancement

#99 mypage_edit 디자인 변경
  team_note.html
Labels: bug

#101 [#100]Feat: 마이페이지 수정, 프로젝트 모집글 동적 js 구현
  css/create.css
  css/mypage.css
  js/01jaeyoung.js
  js/02donggun.js
  mypage_edit.html
  recruit_create.html
Labels: enhancement
