Repository PKNU-JavaStudy/mo.zip_frontend, pull requests merged in 2024-06, with the labels that each got.

#106 [#105]Feat : 백그라운드 컬러피커 기능 추가
  css/team_note.css
  img/banner01.jpg
  index.html
  js/teamnote.js
  team_note.html
Labels: enhancement

#107 Fix/mypage design
  css/mypage.css
  mypage.html
Labels: enhancement

#108 Conflict resolve
  mypage_edit.html
Labels: bug

#110 [#109]Feat: 마이페이지 수정 직군 js 리팩토링
  js/02donggun.js
  team_note.html
Labels: enhancement

#111 style: 팀노트 스타일 수정
  css/team_note.css
Labels: documentation
